steps:
  # Build the main application image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/helloworld:latest', '-f', 'Dockerfile', '.']
    id: 'build-app'

  # Build the verification test image
  # "waitFor": ["-"] starts this immediately (in parallel with the previous step)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld-test:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/helloworld-test:latest', '-f', 'Dockerfile.test', '.']
    id: 'build-test'
    waitFor: ['-']

images:
  - 'gcr.io/$PROJECT_ID/helloworld:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/helloworld:latest'
  - 'gcr.io/$PROJECT_ID/helloworld-test:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/helloworld-test:latest'
