apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo-releasetrain
description: demo-releasetrain
serialPipeline:
  stages:
  - targetId: demo-releasetrain-target-1
    profiles:
    - target-1
    strategy:
      standard:
        verify: true
