apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: helloworld
build:
  artifacts:
    - image: us-docker.pkg.dev/airlock-1p-private-staging/upadhyayshipra-airlock1p-dev/helloworld
      context: .
      docker:
        dockerfile: Dockerfile
    - image: us-docker.pkg.dev/airlock-1p-private-staging/upadhyayshipra-airlock1p-dev/helloworld-test
      context: .
      docker:
        dockerfile: Dockerfile.test
profiles:
  - name: target-1
    manifests:
      rawYaml:
        - service.yaml
    deploy:
      cloudrun: {}
    verify:
      - name: service-check
        container:
          name: service-check
          image: us-docker.pkg.dev/airlock-1p-private-staging/upadhyayshipra-airlock1p-dev/helloworld-test
          command: [ "./verify-service.sh" ]
          env:
            # Pass the region so the script can find the service
            - name: GOOGLE_CLOUD_REGION
              value: "us-central1"
            # Removed SERVICE_URL to force dynamic discovery